[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "postgresql"]

[phases.install]
cmds = ["cd backend && npm install --prefer-offline --no-audit --no-fund --loglevel=error"]
cacheDirectories = ["backend/node_modules"]

[phases.build]
cmds = ["cd backend && npm run build"]
cacheDirectories = ["backend/node_modules", "backend/dist"]

[start]
cmd = "cd backend && node dist/index.js"