# Nixpacks configuration for SolSim backend
[variables]
NODE_ENV = 'production'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'

[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x', 'openssl']

[phases.install]
cmds = [
  'cd backend && npm ci --only=production'
]

[phases.build] 
cmds = [
  'cd backend && npm run build'
]

[start]
cmd = 'cd backend && npm run railway:start'

[buildpack]
type = 'nodejs'