# Railway config for SolSim backend
[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Add memory limits to prevent OOM during export
[deploy.variables]
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_ENV = "production"

[[deploy.healthcheck]]
path = "/health"
port = 4000
