# Railway config for SolSim backend (in backend/ subdirectory)
[build]
buildCommand = "cd backend && npm ci && npm run build"
dockerfilePath = "backend/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "cd backend && npm run railway:start"

# Add memory limits to prevent OOM during export
[deploy.variables]
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[[deploy.healthcheck]]
path = "/health"
port = 4002
