[build]
builder = "NIXPACKS"
# Railway service runs from repository root, so we need to cd into backend
buildCommand = "cd backend && npm ci && npm run build"

[environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
NIXPACKS_BUILD_CMD = "cd backend && npm ci && npm run build"

[deploy]
startCommand = "cd backend && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/health"
port = 4002
