[build]
builder = "NIXPACKS"
# Expect Railway service Root Directory to be set to `backend`
# so commands run inside /app/backend without extra `cd`.
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/health"
port = 4002
