[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "postgresql"]

[phases.install]
cmds = ["rm -rf node_modules/.cache && npm ci --cache /tmp/.npm"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.js"
