# Nixpacks configuration for Railway deployment
# Fixes: "bigint: Failed to load bindings, pure JS will be used"
#
# Native dependencies required for:
# - bigint-buffer (Solana web3.js dependency)
# - Prisma binary compilation
# - Other native Node.js modules
#
# NOTE: Only override the setup phase to add native build tools.
# Railway/nixpacks handles Node.js setup, install, build, and start automatically.

[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "pkg-config"]
