providers = ["node"]

[pkgs]
node = "20"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"

[phases.setup]
cmds = ["echo 'Starting Nixpacks build'"]

[phases.install] 
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc"
]

[start]
cmd = "npm run railway:start"