# Nixpacks configuration for Railway deployment
# Fixes: "bigint: Failed to load bindings, pure JS will be used"
#
# Native dependencies required for:
# - bigint-buffer (Solana web3.js dependency)
# - Prisma binary compilation
# - Other native Node.js modules
#
# NOTE: When specifying nixPkgs, you REPLACE the defaults, so we must include nodejs.

[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake", "pkg-config"]
