[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["openssl", "postgresql", "nodejs-20_x"]

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
PORT = "4002"
