[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --prefer-offline --no-audit --no-fund --loglevel=error && npm run build"
watchPatterns = ["backend/**"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["openssl", "postgresql", "nodejs_20"]

[deploy]
startCommand = "cd backend && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
PORT = "4002"
NIXPACKS_NO_CACHE = "1"
