[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["openssl", "postgresql"]

[deploy]
startCommand = "node dist/start.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
port = 4002
